version: "3.7"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: "Asia/Seoul"
