version: "3.7"

services:
    jenkins:
build:
context: .
dockerfile: jenkins.docker
container_name: jenkins
restart: always
	user: root
	ports:
		- "8080:8080"
	volumes:
		- "/home/jenkins/jenkins_home:/var/jenkins_home"
gitlab:
	image: "gitlab/gitlab-ce:latest"
	container_name: gitlab
	restart: always
	hostname: "10.10.14.128"
	environment:
		GITLAB_OMNIBUS_CONFIG: |
			external_url = "10.10.14.128"
	ports:
		- "80:80"
		- "443:443"
		- "22:22"
	volumes:
		- "/srv/gitlab/config:/etc/gitlab"
		- "/srv/gitlab/logs:/var/log/gitlab"
		- "/srv/gitlab/data:/var/opt/gitlab"
